import React, { useEffect, useMemo, useState } from 'react';
import { subscribeReceipts, FundraisingReceipt } from '../helpers/fundraisingReceipts';
import type { CampaignSummary, FundraisingPledge, FundraisingPledgePayment } from '../helpers/fundraisingCrm';
import type { TempleEvent } from '../helpers/types';
import { buildFundingReport, fundingActivityTotals } from '../helpers/fundraisingReporting';
import { toEasternDateTimeInput } from '../helpers/taskDateTime';
const money = (amount: number | null) => amount === null ? 'Unknown / unverified' : new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(amount);
const FundraisingCombinedReport: React.FC<{ pledges: FundraisingPledge[]; payments: FundraisingPledgePayment[]; campaigns: CampaignSummary[]; events: TempleEvent[] }> = ({ pledges, payments, campaigns, events }) => {
  const [loans, setLoans] = useState<FundraisingReceipt[]>([]); const [donations, setDonations] = useState<FundraisingReceipt[]>([]); const [error, setError] = useState('');
  const [period, setPeriod] = useState<'all' | 'month'>('all'); const [month, setMonth] = useState(toEasternDateTimeInput(new Date()).slice(0, 7));
  const [search, setSearch] = useState(''); const [type, setType] = useState('all'); const [loadedLoans, setLoadedLoans] = useState(false); const [loadedDonations, setLoadedDonations] = useState(false);
  useEffect(() => subscribeReceipts('loan', records => { setLoans(records); setLoadedLoans(true); }, cause => setError(cause.message)), []);
  useEffect(() => subscribeReceipts('donation', records => { setDonations(records); setLoadedDonations(true); }, cause => setError(cause.message)), []);
  const report = useMemo(() => buildFundingReport([...loans, ...donations], pledges, payments, campaigns, events), [loans, donations, pledges, payments, campaigns, events]);
  const nameFor = (id: string) => events.find(event => event.id === id)?.name || campaigns.find(campaign => campaign.eventId === id)?.name || 'General / no event';
  const matches = (record: { name: string; eventId: string; type: string }) => `${record.name} ${nameFor(record.eventId)} ${record.type}`.toLowerCase().includes(search.toLowerCase()) && (type === 'all' || record.type.toLowerCase().startsWith(type));
  const activity = report.activities.filter(item => matches(item) && (period === 'all' || !!month && item.date.startsWith(month))).sort((a, b) => b.date.localeCompare(a.date));
  const totals = fundingActivityTotals(activity);
  const records = report.records.filter(matches).sort((a, b) => b.date.localeCompare(a.date));
  const exportCsv = () => {
    const rows: unknown[][] = [['Financial activity report', period === 'all' ? 'All time' : month], ['Donations received', totals.donations], ['Loans received', totals.loans], ['Pledge payments received', totals.pledgePayments], ['Total cash received', totals.received], ['Loan returns', totals.returns], ['Net tracked cash movement', totals.net], ['New pledge commitments (not cash)', totals.pledged], [], ['Date (Eastern)', 'Activity', 'Donor / lender', 'Event', 'Amount', 'Reference'], ...activity.map(item => [item.date || 'Unknown date', item.type, item.name, nameFor(item.eventId), item.amount, item.reference]), [], ['Current balances—not historic month-end balances'], ['Type', 'Donor / lender', 'Event', 'Date', 'Original amount', 'Received', 'Returned', 'Remaining', 'Source'], ...records.map(item => [item.type, item.name, nameFor(item.eventId), item.date, item.amount, item.received ?? '', item.returned, item.remaining ?? '', item.source])];
    const url = URL.createObjectURL(new Blob(['\uFEFF' + rows.map(row => row.map(cell => `"${String(cell ?? '').replace(/"/g, '""')}"`).join(',')).join('\r\n')], { type: 'text/csv;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = `fundraising-report-${period === 'all' ? 'all-time' : month}.csv`; link.click(); URL.revokeObjectURL(url);
  };
  if (error) return <section className="panel"><p role="alert" className="error-message">Could not load financial report: {error}</p></section>;
  if (!loadedLoans || !loadedDonations) return <section className="panel">Loading financial report…</section>;
  return <section className="panel"><div className="panel-head"><div><h2>Combined fundraising report</h2><p className="muted">Loans, donations, and pledges in one view. Monthly activity uses transaction dates in Eastern Time; balances below are current, not historical month-end balances.</p></div><button className="secondary-btn" onClick={exportCsv} disabled={period === 'month' && !month}>Export report CSV</button></div>
    <div className="fundraising-donor-form"><label><span>Reporting period</span><select value={period} onChange={event => setPeriod(event.target.value as 'all' | 'month')}><option value="all">All time</option><option value="month">Selected month</option></select></label>{period === 'month' && <label><span>Month</span><input type="month" value={month} onChange={event => setMonth(event.target.value)} /></label>}<label><span>Type</span><select value={type} onChange={event => setType(event.target.value)}><option value="all">All types</option><option value="donation">Donations</option><option value="loan">Loans</option><option value="pledge">Pledges</option></select></label><label><span>Search donor / event</span><input value={search} onChange={event => setSearch(event.target.value)} /></label></div>
    <h3>{period === 'all' ? 'All-time recorded activity' : `Recorded activity for ${month || 'selected month'}`}</h3>
    <div className="fundraising-report-grid"><div><span>Donations received</span><strong>{money(totals.donations)}</strong></div><div><span>Loans received</span><strong>{money(totals.loans)}</strong></div><div><span>Pledge payments received</span><strong>{money(totals.pledgePayments)}</strong></div><div><span>Total tracked cash received</span><strong>{money(totals.received)}</strong></div><div><span>Loans returned</span><strong>{money(totals.returns)}</strong></div><div><span>Net tracked cash movement</span><strong>{money(totals.net)}</strong></div><div><span>New pledge commitments—not cash</span><strong>{money(totals.pledged)}</strong></div></div>
    <p className="muted small">Unverified dashboard entries are excluded from cash totals. Historical pledge paid totals without individual receipts cannot be assigned to a month. This is a Hub activity report, not a reconciled QuickBooks accounting report.</p>
    {!!report.activities.filter(item => !item.date).length && <p className="pledge-source-note">{report.activities.filter(item => !item.date).length} activities have no date; included in all-time reporting only.</p>}
    <div className="fundraising-combined-table"><table><thead><tr><th>Date</th><th>Activity</th><th>Donor / lender</th><th>Event</th><th>Amount</th><th>Reference</th></tr></thead><tbody>{activity.map(item => <tr key={`${item.type}:${item.id}`}><td>{item.date || 'Unknown'}</td><td>{item.type}</td><td>{item.name}</td><td>{nameFor(item.eventId)}</td><td>{money(item.amount)}</td><td>{item.reference || '—'}</td></tr>)}</tbody></table>{!activity.length && <p>No activity matches this reporting period.</p>}</div>
    <h3>Combined register · current balances</h3><p className="muted small">All matching records, regardless of selected activity month. Cancelled pledges are excluded. Loan remaining is owed by the Hub; pledge remaining is owed to the Hub. Unknown balances are not treated as zero.</p>
    <div className="fundraising-combined-table"><table><thead><tr><th>Type</th><th>Donor / lender</th><th>Event</th><th>Date</th><th>Original amount</th><th>Received</th><th>Returned</th><th>Remaining</th><th>Source</th></tr></thead><tbody>{records.map(item => <tr key={`${item.type}:${item.id}`}><td>{item.type}</td><td>{item.name}</td><td>{nameFor(item.eventId)}</td><td>{item.date || 'Unknown'}</td><td>{money(item.amount)}</td><td>{money(item.received)}</td><td>{item.type === 'Loan' ? money(item.returned) : '—'}</td><td>{money(item.remaining)}</td><td>{item.source}</td></tr>)}</tbody></table></div>
  </section>;
};
export default FundraisingCombinedReport;
