import React, { useEffect, useMemo, useState } from 'react';
import { CampaignSummary, FundraisingDonor } from '../helpers/fundraisingCrm';
import { TempleEvent } from '../helpers/types';
import { blankReceipt, FundraisingReceipt, LoanRepayment, saveLoanRepayment, saveReceipt, subscribeReceipts } from '../helpers/fundraisingReceipts';
import { toEasternDateTimeInput } from '../helpers/taskDateTime';
import { FundraisingRecordAudit } from './FundraisingAuditHistory';
const money = (amount: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(amount);
const name = (donor: FundraisingDonor) => [donor.firstName, donor.lastName].filter(Boolean).join(' ') || donor.organization;
const modes = ['zelle', 'check', 'cash', 'card', 'bank-transfer', 'other'];
const blankPayment = (): LoanRepayment => ({ id: '', amount: 0, paidDate: '', method: 'zelle', reference: '', paidBy: '', notes: '' });
const FundraisingReceiptsPanel: React.FC<{ kind: 'loan' | 'donation'; donors: FundraisingDonor[]; events: TempleEvent[]; campaigns: CampaignSummary[]; onOpenDonor: (donor: FundraisingDonor) => void }> = ({ kind, donors, events, campaigns, onOpenDonor }) => {
  const [records, setRecords] = useState<FundraisingReceipt[]>([]); const [editing, setEditing] = useState<FundraisingReceipt | null>(null);
  const [search, setSearch] = useState(''); const [sort, setSort] = useState<'asc' | 'desc'>('desc');
  const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [payment, setPayment] = useState(blankPayment());
  const loan = kind === 'loan'; const label = loan ? 'Loan' : 'Donation'; const today = toEasternDateTimeInput(new Date()).slice(0, 10);
  useEffect(() => subscribeReceipts(kind, setRecords, cause => setError(cause.message)), [kind]);
  useEffect(() => { if (!editing) return; const close = (event: KeyboardEvent) => { if (event.key === 'Escape' && !busy) setEditing(null); }; document.addEventListener('keydown', close); return () => document.removeEventListener('keydown', close); }, [editing, busy]);
  const eventName = (id: string) => events.find(event => event.id === id)?.name || campaigns.find(campaign => campaign.eventId === id)?.name || 'General / no event';
  const donationEventDate = (id: string) => {
    const date = events.find(event => event.id === id)?.date;
    return kind === 'donation' && date && Number.isFinite(date.getTime()) ? toEasternDateTimeInput(date).slice(0, 10) : '';
  };
  const all = useMemo(() => {
    const sources = new Set(records.map(record => `${record.eventId}:${record.sourceCampaignEntryId}`));
    const drafts = campaigns.flatMap(campaign => campaign.entries.filter(entry => entry.type === kind && !sources.has(`${campaign.eventId}:${entry.id}`)).map(entry => {
      const donor = donors.find(donor => name(donor).trim().toLowerCase() === `${entry.firstName} ${entry.lastName}`.trim().toLowerCase());
      return { ...blankReceipt(kind), id: `dashboard:${campaign.eventId}:${entry.id}`, eventId: campaign.eventId, sourceCampaignEntryId: entry.id, donorId: donor?.id || '', donorName: `${entry.firstName} ${entry.lastName}`.trim(), amount: entry.amount, notes: entry.comments };
    }));
    return [...records, ...drafts].map(record => {
      const date = events.find(event => event.id === record.eventId)?.date;
      return kind === 'donation' && date && Number.isFinite(date.getTime()) ? { ...record, receivedDate: toEasternDateTimeInput(date).slice(0, 10) } : record;
    });
  }, [records, campaigns, donors, kind, events]);
  const visible = all.filter(record => `${record.donorName} ${eventName(record.eventId)} ${record.notes} ${record.reference} ${record.amount} ${record.receivedDate} ${record.dueDate}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => {
    if (!a.receivedDate !== !b.receivedDate) return a.receivedDate ? -1 : 1;
    return (sort === 'asc' ? 1 : -1) * a.receivedDate.localeCompare(b.receivedDate) || a.id.localeCompare(b.id);
  });
  const current = editing && records.find(record => record.id === editing.id); const remaining = editing ? Math.max(0, editing.amount - (current?.repaidAmount || editing.repaidAmount)) : 0;
  const update = (field: keyof FundraisingReceipt, value: string | number) => setEditing(previous => previous && ({ ...previous, [field]: value }));
  const open = (record: FundraisingReceipt) => { setEditing({ ...record }); setPayment(blankPayment()); setError(''); setMessage(''); };
  const run = async (work: () => Promise<void>) => { setBusy(true); setError(''); setMessage(''); try { await work(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not save.'); } finally { setBusy(false); } };
  const save = () => run(async () => { if (!editing) return; const receivedDate = donationEventDate(editing.eventId) || editing.receivedDate; const result = await saveReceipt({ ...editing, receivedDate, id: editing.id.startsWith('dashboard:') ? '' : editing.id }); setEditing(previous => previous && ({ ...previous, receivedDate, id: result.id })); setMessage(`${label} saved.`); });
  const repay = () => run(async () => { if (!editing) return; await saveLoanRepayment(editing.id, payment); setPayment(blankPayment()); setMessage('Repayment saved and remaining principal updated.'); });
  const exportCsv = () => {
    const rows = [['Donor / lender', 'Event', 'Amount received', 'Date received', 'Payment mode', 'Reference', 'Received by', 'Receipt number', 'Designation', 'Final return date', 'Return mode', 'Frequency', 'Installment amount', 'Next return date', 'Amount returned', 'Remaining', 'Comments', 'Repayment history', 'Source'], ...visible.map(record => [record.donorName, eventName(record.eventId), record.amount, record.receivedDate, record.method, record.reference, record.receivedBy, record.receiptNumber, record.designation, loan ? record.dueDate : '', loan ? record.repaymentMode : '', loan ? record.frequency : '', loan ? record.installmentAmount : '', loan ? record.nextRepaymentDate : '', loan && !record.id.startsWith('dashboard:') ? record.repaidAmount : '', loan && !record.id.startsWith('dashboard:') ? record.amount - record.repaidAmount : '', record.notes, JSON.stringify(record.repayments), record.id.startsWith('dashboard:') ? 'Unverified dashboard entry' : 'Verified receipt'])];
    const url = URL.createObjectURL(new Blob(['\uFEFF' + rows.map(row => row.map(cell => `"${String(cell ?? '').replace(/"/g, '""')}"`).join(',')).join('\r\n')], { type: 'text/csv;charset=utf-8' }));
    const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${kind}s-${today}.csv`; anchor.click(); URL.revokeObjectURL(url);
  };
  return <section className="panel">
    <div className="panel-head"><div><h2>{label}s</h2><p className="muted">{loan ? 'Funds loaned to the Hub; track returns to the lender, in installments or one payment. Principal only—no interest calculation.' : 'One-time donations actually received, with payment and receipt details.'}</p></div><div className="row"><button className="secondary-btn" onClick={exportCsv}>Export CSV</button><button className="primary-btn" onClick={() => open(blankReceipt(kind))}>New {kind}</button></div></div>
    {error && <p className="error-message" role="alert">{error}</p>}{message && <p className="success-message" role="status">{message}</p>}
    <div className="fundraising-pledge-search"><label><span>Search {kind}s</span><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search name, event, amount, reference, or comments" /></label><span>{visible.length} records</span></div>
    <div className="fundraising-report-grid"><div><span>Verified {loan ? 'principal' : 'donations'} received</span><strong>{money(records.reduce((sum, record) => sum + record.amount, 0))}</strong></div>{loan && <><div><span>Returned</span><strong>{money(records.reduce((sum, record) => sum + record.repaidAmount, 0))}</strong></div><div><span>Remaining to return</span><strong>{money(records.reduce((sum, record) => sum + record.amount - record.repaidAmount, 0))}</strong></div></>}</div>
    <div className="fundraising-receipt-head"><span>{loan ? 'Lender / event' : 'Donor / event'}</span><button className="link-btn" onClick={() => setSort(sort === 'asc' ? 'desc' : 'asc')}>Received date {sort === 'desc' ? '↓' : '↑'}</button><span>Amount</span><span>{loan ? 'Returned / remaining' : 'Payment / reference'}</span><span>{loan ? 'Return date / terms' : 'Comments'}</span></div>
    <div className="fundraising-receipt-list">{visible.map(record => { const draft = record.id.startsWith('dashboard:'); return <button key={record.id} onClick={() => open(record)} className={loan && !draft && record.amount > record.repaidAmount && record.dueDate < today ? 'overdue' : ''}><span><strong>{record.donorName}</strong><small>{eventName(record.eventId)}</small>{draft && <small>Dashboard entry · receipt not verified</small>}</span><span>{record.receivedDate || 'Not recorded'}</span><strong>{money(record.amount)}</strong><span>{loan ? draft ? 'Not verified' : `${money(record.repaidAmount)} / ${money(record.amount - record.repaidAmount)}` : `${record.method} · ${record.reference || 'No reference'}`}</span><span>{loan ? `${record.dueDate || 'No date'} · ${record.repaymentMode === 'installments' ? 'Installments' : 'Single return'}` : record.notes || 'No comments'}</span></button>; })}{!visible.length && <p>No {kind}s found.</p>}</div>
    {editing && <div className="modal-backdrop"><section className="panel fundraising-donor-editor" role="dialog" aria-modal="true" aria-label={`${label} record`}><div className="panel-head"><h2>{label} record · {editing.donorName || 'New record'}</h2><button className="secondary-btn" disabled={busy} onClick={() => setEditing(null)}>Close</button></div>
      {error && <p className="error-message" role="alert">{error}</p>}{message && <p className="success-message" role="status">{message}</p>}
      {editing.id.startsWith('dashboard:') && <p className="pledge-source-note">This dashboard entry is not proof of funds received. Verify the actual received date and payment method before saving.</p>}
      <fieldset disabled={busy} className="fundraising-receipt-fieldset"><div className="fundraising-donor-form">
        <label><span>{loan ? 'Linked lender record' : 'Linked donor'} *</span><select value={editing.donorId} onChange={event => update('donorId', event.target.value)}><option value="">Choose donor / lender</option>{donors.filter(donor => !donor.archived).map(donor => <option key={donor.id} value={donor.id}>{name(donor)}</option>)}</select><small>Create a donor in the Donors tab if the person is missing.</small></label>
        <label><span>Event (optional)</span><select disabled={!!editing.sourceCampaignEntryId} value={editing.eventId} onChange={event => update('eventId', event.target.value)}><option value="">General / no event</option>{events.map(event => <option key={event.id} value={event.id}>{event.name}</option>)}</select></label>
        <label><span>{loan ? 'Loan principal received' : 'Donation amount'} *</span><input type="number" min="0.01" step="0.01" value={editing.amount || ''} onChange={event => update('amount', Number(event.target.value))} /></label>
        <label><span>Date received *</span><input type="date" max={today} readOnly={!!donationEventDate(editing.eventId)} value={donationEventDate(editing.eventId) || editing.receivedDate} onChange={event => update('receivedDate', event.target.value)} />{donationEventDate(editing.eventId) && <small>Uses the linked event date (Eastern). Future event dates cannot be recorded as received.</small>}</label>
        <label><span>Payment method *</span><select value={editing.method} onChange={event => update('method', event.target.value)}>{modes.map(mode => <option key={mode}>{mode}</option>)}</select></label>
        <label><span>Received by</span><input list="fundraising-admin-name-options" value={editing.receivedBy} onChange={event => update('receivedBy', event.target.value)} placeholder="Choose fundraising admin or enter a name" /></label>
        <label><span>Reference / check number</span><input value={editing.reference} onChange={event => update('reference', event.target.value)} /></label><label><span>Receipt number</span><input value={editing.receiptNumber} onChange={event => update('receiptNumber', event.target.value)} /></label>
        <label className="full"><span>Fund / purpose / designation</span><input value={editing.designation} onChange={event => update('designation', event.target.value)} /></label>
        {loan && <><h3 className="full">Return terms</h3><label><span>Return arrangement *</span><select value={editing.repaymentMode} onChange={event => update('repaymentMode', event.target.value)}><option value="single">Whole amount at once</option><option value="installments">Installments</option></select></label><label><span>Final return due date *</span><input type="date" min={editing.receivedDate} value={editing.dueDate} onChange={event => update('dueDate', event.target.value)} /></label>{editing.repaymentMode === 'installments' && <><label><span>Installment frequency</span><select value={editing.frequency} onChange={event => update('frequency', event.target.value)}>{['monthly', 'quarterly', 'annual', 'custom'].map(value => <option key={value}>{value}</option>)}</select></label><label><span>Planned installment amount *</span><input type="number" min="0.01" step="0.01" value={editing.installmentAmount || ''} onChange={event => update('installmentAmount', Number(event.target.value))} /></label><label><span>Next installment date *</span><input type="date" min={editing.receivedDate} max={editing.dueDate} value={editing.nextRepaymentDate} onChange={event => update('nextRepaymentDate', event.target.value)} /><small>Update this date as installments are returned.</small></label></>}<label><span>Principal returned (read-only)</span><input readOnly value={money(current?.repaidAmount || editing.repaidAmount)} /></label><label><span>Remaining to return (read-only)</span><input readOnly value={money(remaining)} /></label></>}
        <label className="full"><span>{loan ? 'Loan terms and comments' : 'Donation comments'}</span><textarea rows={6} value={editing.notes} onChange={event => update('notes', event.target.value)} /></label>
        {donors.find(donor => donor.id === editing.donorId) && <button className="secondary-btn" type="button" onClick={() => { const donor = donors.find(donor => donor.id === editing.donorId)!; setEditing(null); onOpenDonor(donor); }}>Open full donor / lender record</button>}
        <button className="primary-btn" type="button" onClick={save}>Save {kind}</button>
      </div></fieldset>
      {editing.id && !editing.id.startsWith('dashboard:') && <FundraisingRecordAudit targetPath={`fundraisingReceipts/${editing.id}`} />}
      {loan && <section className="pledge-payment-history"><h3>Repayment history · money returned to lender</h3>{!editing.id || editing.id.startsWith('dashboard:') ? <p>Save the loan first to record repayments.</p> : <><fieldset disabled={busy} className="fundraising-receipt-fieldset"><div className="fundraising-donor-form"><label><span>Date returned *</span><input type="date" min={editing.receivedDate} max={today} value={payment.paidDate} onChange={event => setPayment({ ...payment, paidDate: event.target.value })} /></label><label><span>Amount returned *</span><input type="number" min="0.01" max={remaining + (current?.repayments.find(item => item.id === payment.id)?.amount || 0)} step="0.01" value={payment.amount || ''} onChange={event => setPayment({ ...payment, amount: Number(event.target.value) })} /></label><label><span>Payment method</span><select value={payment.method} onChange={event => setPayment({ ...payment, method: event.target.value })}>{modes.map(mode => <option key={mode}>{mode}</option>)}</select></label><label><span>Returned by</span><input list="fundraising-admin-name-options" value={payment.paidBy} onChange={event => setPayment({ ...payment, paidBy: event.target.value })} /></label><label><span>Reference / check number</span><input value={payment.reference} onChange={event => setPayment({ ...payment, reference: event.target.value })} /></label><label className="full"><span>Repayment comments</span><textarea rows={3} value={payment.notes} onChange={event => setPayment({ ...payment, notes: event.target.value })} /></label><button className="primary-btn" disabled={!payment.amount || !payment.paidDate} onClick={repay}>{payment.id ? 'Save repayment correction' : 'Record repayment'}</button>{payment.id && <button className="secondary-btn" onClick={() => setPayment(blankPayment())}>Cancel edit</button>}</div></fieldset>
        <div className="pledge-payment-list">{[...(current?.repayments || [])].sort((a, b) => b.paidDate.localeCompare(a.paidDate)).map(item => <article key={item.id}><div><strong>{money(item.amount)}</strong><span>Returned {item.paidDate} · {item.method}</span><span>{item.paidBy || 'No return-person name entered'}</span></div><div><b>{item.reference || 'No reference'}</b><p>{item.notes || 'No comments'}</p><button className="secondary-btn" disabled={busy} onClick={() => setPayment({ ...item })}>Edit repayment</button></div></article>)}</div>{!current?.repayments.length && <p>No repayments recorded.</p>}</> }</section>}
    </section></div>}
  </section>;
};
export default FundraisingReceiptsPanel;
